author: SwearWord
database: false
generator: http://dinnerbone.com/minecraft/tools/pluginator/
main: org.getchunky.chunkyshapes.ChunkyShapes
name: ChunkyShapes
startup: postworld
url: http://getchunky.org/
version: '1.0'
commands:
    draw:
        description: Start drawing the plot.
        usage: /draw
    saveshape:
        description: Save the shape.
        usage: /saveshape